CREATE DATABASE dreamJob ENCODING 'UTF-8';

CREATE TABLE IF NOT EXISTS post (
  id serial PRIMARY KEY,
  name VARCHAR(50) NOT NULL
);
CREATE TABLE IF NOT EXISTS candidate (
 id serial PRIMARY KEY,
 name VARCHAR(50) NOT NULL
);